"""initial phase 2 schema: users, food_entries, exercise_entries

Revision ID: 83581f1cc9d3
Revises: 
Create Date: 2026-06-14 00:07:17.982811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83581f1cc9d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('goal', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('allow_training_use', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('exercise_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=60), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_entries_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_entries_user_id'), ['user_id'], unique=False)

    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish', sa.String(length=120), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('gram_source', sa.String(length=10), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_entries_eaten_at'), ['eaten_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_entries_eaten_at'))

    op.drop_table('food_entries')
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_entries_performed_at'))

    op.drop_table('exercise_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
