"""phase 3 social: friendships, communities, invites, feed, reactions, share defaults

Revision ID: aeafacf0960e
Revises: 83581f1cc9d3
Create Date: 2026-06-14 00:25:57.565862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeafacf0960e'
down_revision: Union[str, Sequence[str], None] = '83581f1cc9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_owner_id'), ['owner_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('share_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('include_food_images', sa.Boolean(), nullable=False),
    sa.Column('include_net_calories', sa.Boolean(), nullable=False),
    sa.Column('include_macros', sa.Boolean(), nullable=False),
    sa.Column('include_target', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'friend_id', name='uq_sharedefault_pair')
    )
    with op.batch_alter_table('share_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_defaults_owner_id'), ['owner_id'], unique=False)

    op.create_table('community_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_invites_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_invites_invitee_id'), ['invitee_id'], unique=False)

    op.create_table('community_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_member_once')
    )
    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_members_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_members_user_id'), ['user_id'], unique=False)

    op.create_table('feed_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_posts_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_posts_created_at'), ['created_at'], unique=False)

    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_post_id'], ['feed_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_post_id', 'user_id', name='uq_reaction_once')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_feed_post_id'), ['feed_post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_feed_post_id'))

    op.drop_table('reactions')
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_feed_posts_community_id'))
        batch_op.drop_index(batch_op.f('ix_feed_posts_author_id'))

    op.drop_table('feed_posts')
    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_members_community_id'))

    op.drop_table('community_members')
    with op.batch_alter_table('community_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_invites_invitee_id'))
        batch_op.drop_index(batch_op.f('ix_community_invites_community_id'))

    op.drop_table('community_invites')
    with op.batch_alter_table('share_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_defaults_owner_id'))

    op.drop_table('share_defaults')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_owner_id'))

    op.drop_table('communities')
    # ### end Alembic commands ###
